#####
## Using a cacheMatrix object, compute and cache the inverse of a matrix
##This program was written for the Programming Assignment 2 as part of the R Programming 
##Course provided by Johns Hopkins faculty through coursera

##Written by: Beth Clymer
##5-20-15

#####
## This function creates a special invertible matrix object that can cache its inverse.
#####
makeCacheMatrix <- function(x = matrix()) {
  inverse <- NULL
  set <- function(y) {
    m <<- y
    inverse <<- NULL
  }
  get <- function() m
  setInverse <- function(computedInverse) inverse <<- computedInverse
  getInverse <- function() inverse
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}

#####
##This function computes the inverse of an invertible matrix object returned 
##by makeCacheMatrix above. If the inverse has already been calculated 
##(and the matrix has not changed), then the cachesolve should retrieve 
##the inverse from the cache, otherwise it will calculate the inverse and 
##cache it within the matrix object generated by makeCacheMatrix. 
#####
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inverse <- x$getInverse()
  if(!is.null(inverse)) {
    message("Retriving previously cached matrix inverse")
    return(inverse)
  }
  message("Computing and caching matrix inverse")
  m <- x$get()
  computedInverse <- solve(m)
  x$setInverse(computedInverse)
  computedInverse
}
